# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zNcwohSbOAajkbIWRvB4G9NDOXlfHKVc
"""

!apt-get install libgeos-3.5.0
!apt-get install libgeos-dev
!pip install https://github.com/matplotlib/basemap/archive/master.zip

!pip install pyproj==1.9.6

from mpl_toolkits.basemap import Basemap
#%matplotlib inline
import matplotlib.pyplot as plt
from google.colab import drive

drive.mount('/content/drive/')

import pandas as pd
df=pd.read_csv('/content/drive/My Drive/covid19.csv')
ser=df["Detected State"].value_counts()
ser.to_csv('state.csv')

ser=pd.read_csv("state.csv")
ser.columns=["state","NO"]
ser=ser[:30]

ff=ser.drop([15 ,17, 27, 29])

ser.to_csv("final.csv")



df=pd.read_csv("final.csv")
df.columns=["num","state","NO"]

df.loc[26].state

df.state[1]='NCT of Delhi'
df=df.drop([15,22])
df.state[26]='Andaman & Nicobar Island'
st=df.state
df2=df.rename({i:st[i] for i in range(len(st)) if i!=15 and i!=22 },axis="index" )
df2["Andaman & Nicobar Island"]=df.loc[26].state
df2.drop( ["state","num"],axis=1,inplace=True)
df2=df2["NO"]

import matplotlib
import matplotlib.pyplot as plt
import matplotlib.cm as cm

import matplotlib
import matplotlib.cm as cm
from matplotlib.patches import Polygon
from matplotlib.collections import PatchCollection
fig=plt.figure(figsize=(13,13))
ax=fig.add_subplot(111)
map=Basemap(projection="lcc",resolution="l",llcrnrlon=67,llcrnrlat=5,urcrnrlon=99,urcrnrlat=37,lat_0=28,lon_0=77)
map.drawcountries(linewidth=2,color='gray')
map.drawmapboundary()
map.drawcoastlines(linewidth=2,color='gray')
map.readshapefile('/content/drive/My Drive/Igismap_3/Indian_States',"Indian_States")
nv=matplotlib.colors.Normalize(vmin=df["NO"].min(),vmax=df["NO"].max())
cmap=cm.RdYlGn
col_map=cm.ScalarMappable(norm=nv,cmap=cmap)
colors=[]
patch=[]
textlis=[]
for x,y in zip(map.Indian_States_info,map.Indian_States) :
  st=x["st_nm"]
  color=color = list(np.random.choice(range(256), size=3) /256 )
  poly=Polygon(np.array(y) ,facecolor=color,edgecolor="white")
  
  if st not in textlis:
    textlis.append(st)
  #  sss="( "+str(df2[st])+" in "+st +" )"
    ax.text(y[0][0]-70000,y[0][1]-90000,st,fontsize=13,color='black')
  ax.add_patch(poly)

  patch.append(poly)
  colors.append(color)

col_map.set_array(np.array(colors))
color_bar=fig.colorbar(col_map,ax=ax,orientation="vertical",label="green to red")

s="Rajasthan"

c=34

"("+s+str(c)+")"

df2

ser=pd.read_csv("state.csv")
ser.columns=["state","NO"]
ser=ser[:30]

ff=ser.drop([15 ,17, 27, 29])

ff.loc[26]

ff.state[26]

